Models/HesabAccount.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HesabDo.Models
{
    public class HesabAccount
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public float Balance { get; set; }
        public string Description { get; set; }

        public IList<HesabAccountUser> HesabAccountUsers { get; set; }

        public IList<Deposit> Deposits { get; set; }
        public IList<Expense> Expenses { get; set; }

    }
}

Controllers/HesabAccountController.cs
using System;
using System.Security.Claims;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HesabDo.Data;
using HesabDo.Models;
using HesabDo.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace HesabDo.Controllers
{
    public class HesabAccountController : Controller
    {
        // GET: /<controller>/
        private readonly UserManager<ApplicationUser> userManager;
        private readonly AppDbContext context;
        private readonly SignInManager<ApplicationUser> signInManager;

        public HesabAccountController(
            SignInManager<ApplicationUser> signInManager, 
            UserManager<ApplicationUser> userManager, 
                                        AppDbContext context)
        {
            this.userManager = userManager;
            this.signInManager = signInManager;
            this.context = context;
        }

        public async Task<IActionResult> Detail(int id)
        {
            DateTime dateTimeNow = DateTime.UtcNow;
            DateTime dateTomorrow = dateTimeNow.Date.AddDays(1);
            var user = await userManager.GetUserAsync(HttpContext.User);
            var data = await context.HesabAccounts.Where(e => e.ID == id).FirstAsync();
            var exp = await context.Expenses.Where(e => e.ApplicationUser.Id == user.Id).Where(e => e.DateTime < dateTomorrow)
                                                .Include(e => e.HesabAccount).OrderByDescending(e => e.DateTime).ToListAsync();
            var dep = await context.Deposits.Where(e => e.ApplicationUser.Id == user.Id).Where(e => e.DateTime < dateTomorrow)
                                                .Include(e => e.HesabAccount)
                                                .OrderByDescending(e => e.DateTime).ToListAsync();
            HesabAccountDetailViewModel model = new HesabAccountDetailViewModel{
                HesabAccount = data,
                Deposits = dep,
                Expenses = exp
            };
            return View(model);
        }


        [AllowAnonymous]
        public async Task<IActionResult> All()
        {
            var data = await context.HesabAccounts.ToListAsync();
            return View(data);
        }

        [AllowAnonymous]
        public async Task<IActionResult> Join(int id)
        {
            var acc = await context.HesabAccounts.Where(c => c.ID == id).FirstAsync();
            var user = await userManager.GetUserAsync(HttpContext.User);
            if (signInManager.IsSignedIn(User))
            {
                HesabAccountUser m = new HesabAccountUser
                {
                    UserID = user.Id,
                    User = user,
                    HesabAccountID = acc.ID,
                    HesabAccount = acc
                };
                await context.HesabAccountUsers.AddAsync(m);
                await context.SaveChangesAsync();

                return RedirectToAction("HesabAccounts", "Account");
            }
            return RedirectToAction("Login", "Account");

        }

        [HttpGet]
        [AllowAnonymous]
        public IActionResult New()
        {
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> New(HesabAccount model)
        {
            
            if (ModelState.IsValid)
            {
                
                HesabAccount newAcc = new HesabAccount
                {
                    Name = model.Name,
                    Balance = model.Balance,
                    Description = model.Description

                };

                await context.HesabAccounts.AddAsync(newAcc);
                await context.SaveChangesAsync();
                return RedirectToAction("All");
            }
            return View(model);
        }
    }
}

Views/HesabAccount/All.cshtml
@model List<HesabAccount>
@{
    ViewBag.Title = "New Account";
}

<h4 class="display-4" align="center">Sare Hesab Accounts</h4>
<br>
@foreach (var a in Model)
{
    <div class="card card-dark bg-dark" style="width: 100%; color: white;">
        <div class="card-body">
            <h5 class="card-title">@a.Name</h5>
            <h6 class="card-subtitle mb-2 text-muted">Rs @a.Balance</h6>
            <p class="lead">@a.Description</p>
            <a class="btn btn-primary" asp-action="Join" asp-controller="HesabAccount" asp-route-id="@a.ID">Join</a>
            <a class="btn btn-primary" asp-action="Detail" asp-controller="HesabAccount" asp-route-id="@a.ID">View</a>
          
        </div>
    </div>
}

Views/HesabAccount/Detail.cshtml
@model HesabAccountDetailViewModel

<div class='row'>
    <div class="col">
        <h3>@Model.HesabAccount.Name</h3>
    </div>
    <div class="col">
        <h3>Balance:<b> @Model.HesabAccount.Balance</b></h3>
    </div>
</div>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark" style="color:white;">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent" align="Center">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" asp-action="Sort" asp-controller="Home" asp-route-table="Expense" asp-route-sortType="All">All</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" asp-action="Sort" asp-controller="Home" asp-route-table="Expense" asp-route-sortType="Today">Today</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" asp-action="Sort" asp-controller="Home" asp-route-table="Expense" asp-route-sortType="Week">This Week</a>
      </li>
      <li class="nav-item ">
        <a class="nav-link" asp-action="Sort" asp-controller="Home" asp-route-table="Expense" asp-route-sortType="DateTime">Oldest First</a>
      </li>
      <li class="nav-item ">
        <a class="nav-link" asp-action="Sort" asp-controller="Home" asp-route-table="Expense" asp-route-sortType="DateTimeDescending">Newest First</a>
      </li>


    </ul>

  </div>
</nav>

    </select>
    <table class="table table-dark">
  <thead>
    <tr>
      <th scope="col">RS</th>
      <th scope="col">What</th>
      <th scope="col">When</th>
      <th scope="col">From</th>
    </tr>
  </thead>
  <tbody>
      @foreach (var a in Model.Expenses)
{
    <tr>
      <td scope="row">@a.Amount</td>
      <td>@a.Description</td>
      <td>@a.DateTime</td>
      <td>@a.ApplicationUser.Email</td>
      <td><a asp-action="DeleteExpense" asp-controller="Home" asp-route-id="@a.ID" class="btn btn-danger">Delete</a></td>
    </tr>
}

    
  </tbody>
</table>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark" style="color:white;">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent" align="Center">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" asp-action="Sort" asp-controller="Home" asp-route-table="Deposit" asp-route-sortType="All">All</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" asp-action="Sort" asp-controller="Home" asp-route-table="Deposit" asp-route-sortType="Today">Today</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" asp-action="Sort" asp-controller="Home" asp-route-table="Deposit" asp-route-sortType="Week">This Week</a>
      </li>
      <li class="nav-item ">
        <a class="nav-link" asp-action="Sort" asp-controller="Home" asp-route-table="Deposit" asp-route-sortType="DateTime">Oldest First</a>
      </li>
      <li class="nav-item ">
        <a class="nav-link" asp-action="Sort" asp-controller="Home" asp-route-table="Deposit" asp-route-sortType="DateTimeDescending">Newest First</a>
      </li>


    </ul>

  </div>
</nav>
</table>
    <table class="table table-dark">
  <thead>
    <tr>
      <th scope="col">RS</th>
      <th scope="col">What</th>
      <th scope="col">When</th>
      <th scope="col">From</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
      @foreach (var a in Model.Deposits)
{
    <tr>
      <td scope="row">@a.Amount</td>
      <td>@a.Description</td>
      <td>@a.DateTime</td>
      <td>@a.ApplicationUser.Email</td>
      <td><a asp-action="DeleteDeposit" asp-controller="Home" asp-route-id="@a.ID" class="btn btn-danger">Delete</a></td>
    </tr>
}

    
  </tbody>
</table>
</div>

</div>

Views/HesabAccount/New.cshtml
@model HesabAccount

@{
    ViewBag.Title = "New Account";
}

<h4 class="display-4" align="center">Kholo Hesab Account</h4>

<br>

<div class="card card-dark bg-dark" style=" color: white;">

<div class="row card-body">
    <div class="col-md-12">
        <form method="post">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="row">
                <div class="col">
                <input type="text" class="form-control" asp-for="Name" placeholder="Name">
                </div>
                <div class="col">
                <input type="text" class="form-control" asp-for="Balance" placeholder="Balance">
                </div>
            </div><br>
            <div class="form-group">
                <input asp-for="Description" placeholder="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>


            <button type="submit" style="width: 100%;" class="btn btn-primary">Kholo</button>


        </form>
    </div>
</div>
</div>